"""add unique constraint to liked

Revision ID: 14576edceb73
Revises: 764ac20f4c0d
Create Date: 2026-07-30 20:44:38.592115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14576edceb73'
down_revision: Union[str, Sequence[str], None] = '764ac20f4c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_song_liked', 'liked', ['user_id', 'song_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_song_liked', 'liked', type_='unique')
    # ### end Alembic commands ###
