"""add indexes on user_id and song_id fk columns

Revision ID: 840eb6d51cab
Revises: f8bf60448c43
Create Date: 2026-09-13 12:05:55.239864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840eb6d51cab'
down_revision: Union[str, Sequence[str], None] = 'f8bf60448c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('playlist_songs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'song_id', name='uq_song_playlist')
    )
    op.create_index(op.f('ix_recently_played_song_id'), 'recently_played', ['song_id'], unique=False)
    op.create_index(op.f('ix_recently_played_user_id'), 'recently_played', ['user_id'], unique=False)
    op.create_index(op.f('ix_songs_user_id'), 'songs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_user_id'), table_name='songs')
    op.drop_index(op.f('ix_recently_played_user_id'), table_name='recently_played')
    op.drop_index(op.f('ix_recently_played_song_id'), table_name='recently_played')
    op.drop_table('playlist_songs')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
